### PR TITLE
legal

### PR DESCRIPTION
**Pull request by miwilc**
officialize some stuff

### CODE REVIEW

**Comment by jrosdahl** [comment]
Wouldn't it be more fitting to include the GPLv2 license text instead of GPLv3 for a GPLv2+ program? :-)

**Comment by miwilc** [comment]
@jrosdahl I suppose but v3 is the updated version , always good to upgrade. :)

**Comment by miwilc** [comment]
@jrosdahl feel free to close this and commit the GPL v2 licence file

**Comment by miwilc** [comment]
@jrosdahl updated licence

**Comment by jrosdahl** [comment]
Applied (squashed), thanks.

**Pull request closed without merging**
