### PR TITLE
Fix server password check, add --cloak option

### PR DESCRIPTION
**Pull request by sometoby**
I hope the purpose of my changes is clear enough. If the current password checking behavior is intentional, I'll remove that change from my PR.

### CODE REVIEW

**Comment by jrosdahl** [comment]
The "Don't convert password to lowercase" commit looks fine. I have no idea why I initially chose to lowercase the password, but it made more sense before 449da7e66ab11 since the given password was lowercased as well before that commit.

Regarding --cloak, why do you want such an option? It doesn't feel very "mini" to me. :slightly_smiling_face:

**Comment by sometoby** [comment]
I prefer the users on my server not to see each other's real hosts for privacy reasons.
I'm don't know about it not feeling "mini"… The patch is fairly mini, though.

**Comment by jrosdahl** [comment]
> I prefer the users on my server not to see each other's real hosts for privacy reasons.

OK. For me, miniircd has always been about "private or internal use", as mentioned in the README, which by extension means that you trust and know everybody (which is why there are no channel operator or IRC operator functionality) and that there should be no need for privacy.

> I don't know about it not feeling "mini"… The patch is fairly mini, though.

I guess the "mini" ship has sailed a long time ago when I accepted stuff like --chroot and SSL support. :slightly_smiling_face:

**Comment by fossdd** [comment]
> > I don't know about it not feeling "mini"… The patch is fairly mini, though.
> 
> I guess the "mini" ship has sailed a long time ago when I accepted stuff like --chroot and SSL support. slightly_smiling_face

It's still mini. Many many IRCd's are today really huge. This keeps beings small in one python script with many options. I really love your work!

**Pull request merged**
